// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvWaNe8-2jR4_QvD34h5iiE88NAcEz4es',
    appId: '1:122134295858:web:f5ff8fac8c9e7f0e62532b',
    messagingSenderId: '122134295858',
    projectId: 'skin-diseases-detection-cefb1',
    authDomain: 'skin-diseases-detection-cefb1.firebaseapp.com',
    storageBucket: 'skin-diseases-detection-cefb1.appspot.com',
    measurementId: 'G-DFHN21QTTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc9Rafu3umJkXapjC63FELkqcR4Ty9QP0',
    appId: '1:122134295858:android:c74e76d9bd41c7ec62532b',
    messagingSenderId: '122134295858',
    projectId: 'skin-diseases-detection-cefb1',
    storageBucket: 'skin-diseases-detection-cefb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_eqV6Ez-Ig89SgGQvoLax4IYcHs2fSGo',
    appId: '1:122134295858:ios:f5158ec5a50cddea62532b',
    messagingSenderId: '122134295858',
    projectId: 'skin-diseases-detection-cefb1',
    storageBucket: 'skin-diseases-detection-cefb1.appspot.com',
    iosBundleId: 'com.example.skinDiseasesDetectionSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_eqV6Ez-Ig89SgGQvoLax4IYcHs2fSGo',
    appId: '1:122134295858:ios:16585d73ab07624862532b',
    messagingSenderId: '122134295858',
    projectId: 'skin-diseases-detection-cefb1',
    storageBucket: 'skin-diseases-detection-cefb1.appspot.com',
    iosBundleId: 'com.example.skinDiseasesDetectionSystem.RunnerTests',
  );
}
